import argparse
import csv
import subprocess
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent

BASE_DIR = SCRIPT_DIR / "bugs4q-robust"
OUTPUT_CSV = SCRIPT_DIR / "execution_results.csv"
LOG_DIR = SCRIPT_DIR / "logs"

NUM_RUNS = 30
TIMEOUT_SEC = 60


def run_test(project_dir: Path, test_file: Path, target_file: Path) -> tuple[str, str, str]:
    """
    Execute a test file against a target program.

    Returns:
        A tuple of (status, stdout, stderr).
    """
    if not test_file.exists():
        return "MissingTest", "", f"Missing test file: {test_file.name}"

    if not target_file.exists():
        return "MissingTarget", "", f"Missing target file: {target_file.name}"

    try:
        completed = subprocess.run(
            ["python", test_file.name, target_file.name],
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=TIMEOUT_SEC,
        )

        status = "Pass" if completed.returncode == 0 else "Fail"
        return status, completed.stdout, completed.stderr

    except subprocess.TimeoutExpired as e:
        stdout = e.stdout if isinstance(e.stdout, str) else (e.stdout or b"").decode(errors="replace")
        stderr = e.stderr if isinstance(e.stderr, str) else (e.stderr or b"").decode(errors="replace")
        return "Timeout", stdout, stderr + f"\nTimeout after {TIMEOUT_SEC} seconds."

    except Exception as e:
        return "Fail", "", f"{type(e).__name__}: {e}"


def write_log(log_path: Path, stdout: str, stderr: str) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)

    with log_path.open("w", encoding="utf-8") as f:
        f.write("--- STDOUT ---\n")
        f.write(stdout or "")
        f.write("\n--- STDERR ---\n")
        f.write(stderr or "")
        f.write("\n")


def cleanup_side_effects(project_dir: Path) -> None:
    """
    Remove common side-effect files generated by some artifacts.

    Add file names here if more temporary files appear.
    """
    removable_files = [
        "out.png",
        "result.txt",
    ]

    for name in removable_files:
        path = project_dir / name
        if path.exists() and path.is_file():
            path.unlink()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Execute Bugs4Q+ artifacts and save per-run results and logs."
    )
    parser.add_argument(
        "artifact_id",
        nargs="?",
        type=int,
        help="Artifact ID to execute. If omitted, all artifacts are executed.",
    )
    args = parser.parse_args()

    if not BASE_DIR.exists():
        raise FileNotFoundError(f"Dataset directory not found: {BASE_DIR}")

    if args.artifact_id is None:
        project_dirs = sorted(
            [p for p in BASE_DIR.iterdir() if p.is_dir() and p.name.isdigit()],
            key=lambda p: int(p.name),
        )
    else:
        project_dirs = [BASE_DIR / str(args.artifact_id)]

    rows = []
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    for project_dir in project_dirs:
        if not project_dir.exists():
            print(f"Skip: missing artifact directory: {project_dir}")
            continue

        artifact_id = project_dir.name

        test_file = project_dir / "test.py"
        buggy_file = project_dir / "buggy.py"
        fixed_file = project_dir / "fixed.py"

        project_log_dir = LOG_DIR / artifact_id
        project_log_dir.mkdir(parents=True, exist_ok=True)

        print(f"== Artifact {artifact_id} ==")

        for run_id in range(1, NUM_RUNS + 1):
            row = {
                "id": artifact_id,
                "run": run_id,
                "test_buggy": "",
                "test_fixed": "",
            }

            buggy_status, buggy_stdout, buggy_stderr = run_test(
                project_dir=project_dir,
                test_file=test_file,
                target_file=buggy_file,
            )
            row["test_buggy"] = buggy_status

            write_log(
                project_log_dir / f"test_buggy_run{run_id:02d}.log",
                buggy_stdout,
                buggy_stderr,
            )

            print(f"[{artifact_id}] run {run_id:02d} buggy: {buggy_status}")
            if buggy_stdout:
                print(buggy_stdout, end="")
            if buggy_stderr:
                print(buggy_stderr, end="")

            fixed_status, fixed_stdout, fixed_stderr = run_test(
                project_dir=project_dir,
                test_file=test_file,
                target_file=fixed_file,
            )
            row["test_fixed"] = fixed_status

            write_log(
                project_log_dir / f"test_fixed_run{run_id:02d}.log",
                fixed_stdout,
                fixed_stderr,
            )

            print(f"[{artifact_id}] run {run_id:02d} fixed: {fixed_status}")
            if fixed_stdout:
                print(fixed_stdout, end="")
            if fixed_stderr:
                print(fixed_stderr, end="")

            rows.append(row)

            cleanup_side_effects(project_dir)

    with OUTPUT_CSV.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "id",
                "run",
                "test_buggy",
                "test_fixed",
            ],
        )
        writer.writeheader()
        writer.writerows(rows)

    print(f"Execution results are saved at {OUTPUT_CSV}.")
    print(f"Logs are saved under {LOG_DIR}/")


if __name__ == "__main__":
    main()