FROM python:3.10.20

ARG QISKIT_VERSION=2.3.1

RUN apt-get update \
    && apt-get install -y vim build-essential tree procps parallel \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -g 1000 appuser \
    && useradd -m -u 1000 -g 1000 -s /bin/bash appuser

WORKDIR /src

COPY requirements/ /src/requirements/
COPY bash_setting /home/appuser/.bashrc

RUN pip install --upgrade pip
RUN pip install -r /src/requirements/base-requirements.txt
RUN pip install -r /src/requirements/qiskit2/${QISKIT_VERSION}.txt

ENV HOME=/home/appuser

RUN chown -R 1000:1000 /home/appuser /src

USER appuser